name: Copy Files from GameDevAI to GameDevAIWeb

on:
  workflow_dispatch:
    inputs:
      commit_message:
        description: 'Commit message for the changes'
        required: true
        default: 'Sync files from GameDevAI web-interface branch'
      copy_all_files:
        description: 'Copy all files (otherwise only specific project files)'
        required: true
        default: 'true'
        type: boolean

jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GameDevAI repository (source)
        uses: actions/checkout@v4
        with:
          repository: TimurPshITMO/GameDevAI
          ref: web-interface
          token: ${{ secrets.SOURCE_REPO_TOKEN }}
          path: source-repo

      - name: Checkout GameDevAIWeb repository (target)
        uses: actions/checkout@v4
        with:
          repository: TimurPshITMO/GameDevAIWeb
          ref: main
          token: ${{ secrets.TARGET_REPO_TOKEN }}
          path: target-repo

      - name: Copy project files (optimized for React/Vite)
        if: ${{ inputs.copy_all_files == 'false' }}
        run: |
          # Создаем необходимые директории
          mkdir -p target-repo/src
          
          # Копируем только необходимые файлы проекта
          cp -R source-repo/src target-repo/
          cp source-repo/vite.config.js target-repo/
          cp source-repo/package.json target-repo/
          cp source-repo/package-lock.json target-repo/
          cp source-repo/index.html target-repo/
          cp -R source-repo/public target-repo/
          
          # Удаляем .gitignore если он есть, чтобы не перезаписать целевой
          rm -f target-repo/.gitignore

      - name: Copy all files
        if: ${{ inputs.copy_all_files == 'true' }}
        run: |
          # Копируем все файлы из source-repo в target-repo
          rsync -av --exclude='.git' source-repo/ target-repo/

      - name: Commit and push changes to GameDevAIWeb
        run: |
          cd target-repo
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          # Проверяем, есть ли изменения
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "${{ github.event.inputs.commit_message }}"
            git push "https://x-access-token:${{ secrets.TARGET_REPO_TOKEN }}@github.com/TimurPshITMO/GameDevAIWeb.git" main
            echo "✅ Changes pushed successfully to GameDevAIWeb"
          else
            echo "ℹ️ No changes to commit"
          fi